/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 model.glb
Author: TreDè (https://sketchfab.com/luigi_disilvestre)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/vr-meta-meeting-island-disco-party-baked-a7b5795d254e4ab1b0318ae0a3974916
Title: VR Meta Meeting Island & Disco Party | Baked
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-673.017, 47.995, 311.806]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <group position={[27.3, 9.373, -1.09]} rotation={[0, 0, -0.224]} scale={0.613}>
            <mesh geometry={nodes.Cube005_Marble_0.geometry} material={materials.Marble} />
            <mesh geometry={nodes.Cube005_Emission_0.geometry} material={materials.Emission} />
          </group>
          <group position={[29.035, 5.731, -1.09]} rotation={[0, 0, 1.348]} scale={0.613}>
            <mesh geometry={nodes.Cube011_Marble_0.geometry} material={materials.Marble} />
            <mesh geometry={nodes.Cube011_Emission_0.geometry} material={materials.Emission} />
          </group>
          <group position={[28.162, 2.309, -1.09]} rotation={[0, 0, -1.794]} scale={0.613}>
            <mesh geometry={nodes.Cube013_Marble_0.geometry} material={materials.Marble} />
            <mesh geometry={nodes.Cube013_Emission_0.geometry} material={materials.Emission} />
          </group>
          <group position={[24.851, -0.518, -1.09]} rotation={[0, 0, -0.224]} scale={0.613}>
            <mesh geometry={nodes.Cube015_Marble_0.geometry} material={materials.Marble} />
            <mesh geometry={nodes.Cube015_Emission_0.geometry} material={materials.Emission} />
          </group>
          <group position={[26.522, -4.498, -1.09]} rotation={[0, 0, 1.348]} scale={0.613}>
            <mesh geometry={nodes.Cube018_Marble_0.geometry} material={materials.Marble} />
            <mesh geometry={nodes.Cube018_Emission_0.geometry} material={materials.Emission} />
          </group>
          <group position={[25.677, -7.834, -1.09]} rotation={[0, 0, -1.794]} scale={0.613}>
            <mesh geometry={nodes.Cube020_Marble_0.geometry} material={materials.Marble} />
            <mesh geometry={nodes.Cube020_Emission_0.geometry} material={materials.Emission} />
          </group>
          <group position={[22.365, -10.662, -1.09]} rotation={[0, 0, -0.224]} scale={0.613}>
            <mesh geometry={nodes.Cube022_Marble_0.geometry} material={materials.Marble} />
            <mesh geometry={nodes.Cube022_Emission_0.geometry} material={materials.Emission} />
          </group>
          <group position={[30.534, 12.463, -1.09]} rotation={[0, 0, -1.794]} scale={0.613}>
            <mesh geometry={nodes.Cube028_Marble_0.geometry} material={materials.Marble} />
            <mesh geometry={nodes.Cube028_Emission_0.geometry} material={materials.Emission} />
          </group>
          <mesh geometry={nodes.Cube003_Leather_0.geometry} material={materials.Leather} position={[29.035, 5.731, -1.09]} rotation={[0, 0, 1.348]} scale={0.613} />
          <mesh geometry={nodes.Cube004_Leather_0.geometry} material={materials.Leather} position={[27.3, 9.373, -1.09]} rotation={[0, 0, -0.224]} scale={0.613} />
          <mesh geometry={nodes.Cube010_Marble_0.geometry} material={materials.Marble} position={[29.802, 8.737, -0.559]} rotation={[0, 0, -0.224]} scale={0.677} />
          <mesh geometry={nodes.Cube012_Leather_0.geometry} material={materials.Leather} position={[28.162, 2.309, -1.09]} rotation={[0, 0, -1.794]} scale={0.613} />
          <mesh geometry={nodes.Cube014_Leather_0.geometry} material={materials.Leather} position={[24.851, -0.518, -1.09]} rotation={[0, 0, -0.224]} scale={0.613} />
          <mesh geometry={nodes.Cube016_Marble_0.geometry} material={materials.Marble} position={[27.411, -1.024, -0.559]} rotation={[0, 0, -0.224]} scale={0.677} />
          <mesh geometry={nodes.Cube017_Leather_0.geometry} material={materials.Leather} position={[26.522, -4.498, -1.09]} rotation={[0, 0, 1.348]} scale={0.613} />
          <mesh geometry={nodes.Cube019_Leather_0.geometry} material={materials.Leather} position={[25.677, -7.834, -1.09]} rotation={[0, 0, -1.794]} scale={0.613} />
          <mesh geometry={nodes.Cube021_Leather_0.geometry} material={materials.Leather} position={[22.365, -10.662, -1.09]} rotation={[0, 0, -0.224]} scale={0.613} />
          <mesh geometry={nodes.Cube023_Marble_0.geometry} material={materials.Marble} position={[24.926, -11.167, -0.559]} rotation={[0, 0, -0.224]} scale={0.677} />
          <mesh geometry={nodes.Plane012_Pillow_0.geometry} material={materials.Pillow} position={[22.166, -9.798, -0.729]} rotation={[0.241, 0.809, -0.328]} scale={0.347} />
          <mesh geometry={nodes.Dechchair003_Leather_0.geometry} material={materials.Leather} position={[6.166, -8.907, -1.621]} rotation={[Math.PI / 2, 1.298, 0]} scale={1.152} />
          <mesh geometry={nodes.Dechchair004_Leather_0.geometry} material={materials.Leather} position={[4.158, -8.567, -1.621]} rotation={[Math.PI / 2, 1.539, 0]} scale={1.152} />
          <mesh geometry={nodes.Dechchair005_Leather_0.geometry} material={materials.Leather} position={[14.07, -10.522, -1.621]} rotation={[Math.PI / 2, 1.242, 0]} scale={1.152} />
          <mesh geometry={nodes.Dechchair006_Leather_0.geometry} material={materials.Leather} position={[12.084, -10.07, -1.621]} rotation={[Math.PI / 2, 1.483, 0]} scale={1.152} />
          <mesh geometry={nodes.Dechchair007_Leather_0.geometry} material={materials.Leather} position={[16.348, -11.202, -1.621]} rotation={[Math.PI / 2, 1.242, 0]} scale={1.152} />
          <mesh geometry={nodes.Cube027_Leather_0.geometry} material={materials.Leather} position={[30.534, 12.463, -1.09]} rotation={[0, 0, -1.794]} scale={0.613} />
          <mesh geometry={nodes.Plane001_Pillow_0.geometry} material={materials.Pillow} position={[25.025, -7.244, -0.729]} rotation={[0.822, -0.176, -1.732]} scale={0.347} />
          <mesh geometry={nodes.Plane002_Pillow_0.geometry} material={materials.Pillow} position={[24.668, 0.342, -0.729]} rotation={[-0.146, 0.827, 0.197]} scale={0.347} />
          <mesh geometry={nodes.Plane004_Pillow_0.geometry} material={materials.Pillow} position={[24.527, -0.273, -0.729]} rotation={[0.325, 0.785, -0.445]} scale={0.347} />
          <mesh geometry={nodes.Plane008_Pillow_0.geometry} material={materials.Pillow} position={[30.959, 12.735, -0.729]} rotation={[0.831, 0.113, -1.468]} scale={0.347} />
          <mesh geometry={nodes.Plane009_Pillow_0.geometry} material={materials.Pillow} position={[30.342, 12.864, -0.729]} rotation={[0.815, -0.214, -1.768]} scale={0.347} />
          <mesh geometry={nodes.Plane010_Pillow_0.geometry} material={materials.Pillow} position={[28.848, 5.309, -0.729]} rotation={[-0.833, 0.082, 1.496]} scale={0.347} />
        </group>
        <group position={[774.744, -147.382, -135.583]} rotation={[-Math.PI / 2, 0, 0]} scale={3478.551}>
          <mesh geometry={nodes.Plane_Marble_0.geometry} material={materials.Marble} />
          <mesh geometry={nodes.Plane_Grass_0.geometry} material={materials.Grass} />
        </group>
        <group position={[1041.35, 111.298, -1410.82]} rotation={[-Math.PI / 2, 0, -0.233]} scale={236.569}>
          <mesh geometry={nodes.DJ_BlackMetal_0.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.DJ_Marble_0.geometry} material={materials.Marble} />
          <mesh geometry={nodes.DJ_Emission_0.geometry} material={materials.Emission} />
        </group>
        <group position={[-2872.686, 506.333, -3800.238]} rotation={[-Math.PI / 2, 0, 0]} scale={36.72}>
          <group position={[-1.293, 0, -3.334]}>
            <mesh geometry={nodes.plams_PalmBark_0.geometry} material={materials.PalmBark} />
            <mesh geometry={nodes.plams_PalmLeaf_0.geometry} material={materials.PalmLeaf} />
          </group>
          <group position={[-1.293, -198.533, -3.334]}>
            <mesh geometry={nodes.palms2_PalmBark_0.geometry} material={materials.PalmBark} />
            <mesh geometry={nodes.palms2_PalmLeaf_0.geometry} material={materials.PalmLeaf} />
          </group>
        </group>
        <group position={[337.011, 149.708, -1777.704]} rotation={[0, -0.22, 0]} scale={65.091}>
          <mesh geometry={nodes.Panel_BlackMetal_0.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Panel_Emission_0.geometry} material={materials.Emission} />
        </group>
        <group position={[1817.326, 149.708, -1431.073]} rotation={[0, -0.22, 0]} scale={65.091}>
          <mesh geometry={nodes.Panel001_BlackMetal_0.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Panel001_Emission_0.geometry} material={materials.Emission} />
        </group>
        <group position={[-1232.764, -133.572, 1188.011]} rotation={[0, -0.219, 0]} scale={[8.496, 8.496, 14.744]}>
          <mesh geometry={nodes.Poollights_BlackMetal_0.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Poollights_Poollight_0.geometry} material={materials.Poollight} />
        </group>
        <group position={[770.044, 47.995, -135.903]} rotation={[-0.615, Math.PI / 6, -0.615]} scale={72.956}>
          <mesh geometry={nodes.CUBE_Marble_0.geometry} material={materials.Marble} />
          <mesh geometry={nodes.CUBE_Emission_0.geometry} material={materials.Emission} />
        </group>
        <group position={[1004.164, 20.951, -1282.687]} rotation={[-Math.PI / 2, 0, -0.239]} scale={100}>
          <mesh geometry={nodes.Cube001_Marble_0.geometry} material={materials.Marble} />
          <mesh geometry={nodes.Cube001_Mixer_0.geometry} material={materials.Mixer} />
        </group>
        <group position={[870.831, 228.791, -1235.579]} rotation={[0.407, -0.579, -1.34]} scale={11.571}>
          <mesh geometry={nodes.Spotlight001_BlackMetal_0.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Spotlight001_Emission_0.geometry} material={materials.Emission} />
        </group>
        <mesh geometry={nodes.Sphere004_Emission_0.geometry} material={materials.Emission} position={[2031.376, -94.477, 1748.742]} rotation={[-Math.PI / 2, 0, 0]} scale={30.631} />
        <mesh geometry={nodes.Sphere005_Emission_0.geometry} material={materials.Emission} position={[1994.632, -94.477, 1680.697]} rotation={[-Math.PI / 2, 0, 0]} scale={30.631} />
        <mesh geometry={nodes.Sphere006_Emission_0.geometry} material={materials.Emission} position={[2267.224, -94.477, 466.418]} rotation={[-Math.PI / 2, 0, -1.389]} scale={30.631} />
        <mesh geometry={nodes.Sphere007_Emission_0.geometry} material={materials.Emission} position={[2327.488, -94.477, 417.957]} rotation={[-Math.PI / 2, 0, -1.389]} scale={30.631} />
        <mesh geometry={nodes.Sphere008_Emission_0.geometry} material={materials.Emission} position={[2556.3, -94.477, -643.49]} rotation={[-Math.PI / 2, 0, -1.389]} scale={30.631} />
        <mesh geometry={nodes.Sphere009_Emission_0.geometry} material={materials.Emission} position={[2678.63, -94.477, -1337.147]} rotation={[-Math.PI / 2, 0, 0.329]} scale={30.631} />
        <mesh geometry={nodes.Sphere010_Emission_0.geometry} material={materials.Emission} position={[2621.852, -94.477, -1389.649]} rotation={[-Math.PI / 2, 0, 0.329]} scale={30.631} />
        <mesh geometry={nodes.Sphere011_Emission_0.geometry} material={materials.Emission} position={[251.499, -94.477, 1371.326]} rotation={[-Math.PI / 2, 0, 1.607]} scale={30.631} />
        <mesh geometry={nodes.Sphere012_Emission_0.geometry} material={materials.Emission} position={[184.844, -94.477, 1410.535]} rotation={[-Math.PI / 2, 0, 1.607]} scale={30.631} />
        <mesh geometry={nodes.Sphere013_Emission_0.geometry} material={materials.Emission} position={[1136.225, -94.477, 1626.395]} rotation={[-Math.PI / 2, 0, 1.607]} scale={30.631} />
        <mesh geometry={nodes.Sphere_Emission_0.geometry} material={materials.Emission} position={[-1255.924, -35.655, 881.797]} rotation={[-Math.PI / 2, 0, 0]} scale={30.631} />
        <mesh geometry={nodes.Sphere014_Emission_0.geometry} material={materials.Emission} position={[-833.833, -35.655, 424.411]} rotation={[-Math.PI / 2, 0, 2.656]} scale={30.631} />
        <mesh geometry={nodes.Cube_CubeHouse_0.geometry} material={materials.CubeHouse} position={[-1039.802, 174.482, 1030.15]} rotation={[-Math.PI / 2, 0, 1.898]} scale={251.939} />
        <mesh geometry={nodes.Cube007_CubeHouse2_0.geometry} material={materials.CubeHouse2} position={[-892.495, 174.482, 212.348]} rotation={[-Math.PI / 2, 0, -1.729]} scale={251.939} />
        <mesh geometry={nodes.Dechchair001_Leather_0.geometry} material={materials.Leather} position={[-1004.024, -63.133, 1142.186]} rotation={[0, 0.217, 0]} scale={115.163} />
        <mesh geometry={nodes.Dechchair002_Leather_0.geometry} material={materials.Leather} position={[-1068.426, -63.133, 948.981]} rotation={[0, 0.458, 0]} scale={115.163} />
        <mesh geometry={nodes.Dechchair008_Leather_0.geometry} material={materials.Leather} position={[-905.07, -63.133, 297.493]} rotation={[0, -0.269, 0]} scale={115.163} />
        <mesh geometry={nodes.Dechchair009_Leather_0.geometry} material={materials.Leather} position={[-871.84, -63.133, 96.566]} rotation={[0, -0.028, 0]} scale={115.163} />
        <mesh geometry={nodes.Plane003_curtain_0.geometry} material={materials.curtain} position={[-1309.127, 155.325, 1024.769]} rotation={[0, -1.257, -Math.PI / 2]} scale={157.916} />
        <mesh geometry={nodes.Plane005_curtain_0.geometry} material={materials.curtain} position={[-656.825, 155.325, 342.825]} rotation={[0, 1.399, -Math.PI / 2]} scale={157.916} />
        <mesh geometry={nodes.Sphere003_Emission_0.geometry} material={materials.Emission} position={[-497.541, -35.655, -1198.615]} rotation={[-Math.PI / 2, 0, 2.095]} scale={30.631} />
        <mesh geometry={nodes.Sphere015_Emission_0.geometry} material={materials.Emission} position={[-540.425, -35.655, -1249.197]} rotation={[-Math.PI / 2, 0, 2.095]} scale={30.631} />
        <mesh geometry={nodes.Cube008_CubeHouse_0.geometry} material={materials.CubeHouse} position={[-694.915, 174.482, -587.487]} rotation={[-Math.PI / 2, 0, 1.103]} scale={251.939} />
        <mesh geometry={nodes.Cube009_CubeHouse2_0.geometry} material={materials.CubeHouse2} position={[-477.291, 174.482, -1459.972]} rotation={[-Math.PI / 2, 0, -2.29]} scale={251.939} />
        <mesh geometry={nodes.Dechchair010_Leather_0.geometry} material={materials.Leather} position={[-749.887, -63.133, -483.515]} rotation={[0, -0.579, 0]} scale={115.163} />
        <mesh geometry={nodes.Dechchair011_Leather_0.geometry} material={materials.Leather} position={[-656.979, -63.133, -664.744]} rotation={[0, -0.338, 0]} scale={115.163} />
        <mesh geometry={nodes.Dechchair012_Leather_0.geometry} material={materials.Leather} position={[-533.233, -63.133, -1394.563]} rotation={[0, -0.83, 0]} scale={115.163} />
        <mesh geometry={nodes.Dechchair013_Leather_0.geometry} material={materials.Leather} position={[-398.211, -63.133, -1547.025]} rotation={[0, -0.589, 0]} scale={115.163} />
        <mesh geometry={nodes.Plane006_curtain_0.geometry} material={materials.curtain} position={[-879.584, 155.325, -783.604]} rotation={[-Math.PI, -1.089, Math.PI / 2]} scale={157.916} />
        <mesh geometry={nodes.Plane007_curtain_0.geometry} material={materials.curtain} position={[-347.139, 155.325, -1224.122]} rotation={[0, 0.838, -Math.PI / 2]} scale={157.916} />
        <mesh geometry={nodes.Sphere001_Emission_0.geometry} material={materials.Emission} position={[-770.613, -35.655, 444.431]} rotation={[-Math.PI / 2, 0, 2.656]} scale={30.631} />
        <mesh geometry={nodes.Sphere002_Emission_0.geometry} material={materials.Emission} position={[-740.236, -35.655, -845.68]} rotation={[-Math.PI / 2, 0, -0.795]} scale={30.631} />
        <mesh geometry={nodes.Floor_Floor_0.geometry} material={materials.Floor} position={[774.744, -119.844, -135.583]} rotation={[-Math.PI / 2, 0, -0.214]} scale={1717.326} />
        <mesh geometry={nodes.Speaker_Speaker_0.geometry} material={materials.Speaker} position={[606.329, -45.677, -1220.838]} rotation={[-Math.PI / 2, 0, -0.196]} scale={[40.109, 40.109, 72.295]} />
        <mesh geometry={nodes.Water_Water_0.geometry} material={materials.Water} position={[774.744, -147.382, -135.583]} rotation={[-Math.PI / 2, 0, 0]} scale={3478.551} />
        <mesh geometry={nodes.Text_Emission_0.geometry} material={materials.Emission} position={[309.563, -25.62, -1763.065]} rotation={[0, -0.218, 0]} scale={41.936} />
        <mesh geometry={nodes.Text001_Emission_0.geometry} material={materials.Emission} position={[1789.879, -25.62, -1416.434]} rotation={[0, -0.218, 0]} scale={41.936} />
        <mesh geometry={nodes.Pool_leds_Poollight_0.geometry} material={materials.Poollight} position={[774.744, -199.34, -135.583]} rotation={[-Math.PI / 2, 0, -0.214]} scale={1717.326} />
        <mesh geometry={nodes.Glass_Glass_0.geometry} material={materials.Glass} position={[774.744, -147.382, -135.583]} rotation={[-Math.PI / 2, 0, 0]} scale={3478.551} />
        <mesh geometry={nodes.Speaker001_Speaker_0.geometry} material={materials.Speaker} position={[606.564, 97.426, -1222.717]} rotation={[-1.61, 0, -0.19]} scale={[40.109, 40.109, 72.295]} />
        <mesh geometry={nodes.Speaker002_Speaker_0.geometry} material={materials.Speaker} position={[1325.989, -45.677, -1047.823]} rotation={[-Math.PI / 2, 0, -0.3]} scale={[40.109, 40.109, 72.295]} />
        <mesh geometry={nodes.Speaker003_Speaker_0.geometry} material={materials.Speaker} position={[1326.417, 97.426, -1049.667]} rotation={[-1.61, 0.004, -0.294]} scale={[40.109, 40.109, 72.295]} />
        <mesh geometry={nodes.Skybox_HDRI_0.geometry} material={materials.HDRI} position={[763.592, 47.995, -121.887]} rotation={[-Math.PI / 2, 0, 0.912]} scale={11784} />
        <mesh geometry={nodes.collisions_Collisions_0.geometry} material={materials.Collisions} position={[774.744, -119.844, -135.583]} rotation={[-Math.PI / 2, 0, -0.214]} scale={1717.326} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
